import Foundation
import Models
import SwiftData
import XCTest
@testable import MemoData

@MainActor
// android-v1.zip was generated by the unmodified Kotlin LocalBackupArchive.write
// on MoeMemosAndroid feat/local-backup-restore, commit 01e50d06edee69118ffb1b7cae31484e83291c23.
final class LocalBackupServiceTests: XCTestCase {
    private func container() throws -> ModelContainer {
        try ModelContainer(for: User.self, StoredMemo.self, StoredResource.self,
                           configurations: ModelConfiguration(isStoredInMemoryOnly: true))
    }

    private func memo(_ context: ModelContext, account: String = "local", id: String? = nil) -> StoredMemo {
        let memo = StoredMemo(accountKey: account, content: "# preserved\r\n", pinned: true, rowStatus: .archived,
            visibility: .local, createdAt: Date(timeIntervalSince1970: 1_700_000_000.123456), updatedAt: Date(timeIntervalSince1970: 1_700_000_100.5))
        memo.backupId = id
        context.insert(memo)
        return memo
    }

    func testRestoreIsAdditiveIdempotentAndIsolatedFromRemoteAccounts() async throws {
        let directory = FileManager.default.temporaryDirectory.appendingPathComponent(UUID().uuidString)
        defer { try? FileManager.default.removeItem(at: directory) }
        let sourceContainer = try container()
        let source = ModelContext(sourceContainer)
        let original = memo(source)
        try source.save()
        let exporter = LocalBackupService(container: sourceContainer)
        let zip = try await exporter.export()
        defer { try? FileManager.default.removeItem(at: zip) }
        let exportedAgain = try await exporter.export()
        defer { try? FileManager.default.removeItem(at: exportedAgain) }
        let first = try await exporter.prepareImport(from: zip)
        let second = try await exporter.prepareImport(from: exportedAgain)
        XCTAssertEqual(first.data.manifest.memos[0].id, second.data.manifest.memos[0].id)
        XCTAssertEqual(first.preview.existingMemos, 1)

        let destination = try container()
        let initialContext = ModelContext(destination)
        _ = memo(initialContext, account: "remote", id: first.data.manifest.memos[0].id)
        let kept = memo(initialContext, id: "keep-me")
        kept.content = "existing local content"
        try initialContext.save()
        let service = LocalBackupService(container: destination, resourceDirectory: directory)
        let prepared = try await service.prepareImport(from: zip)
        XCTAssertEqual(prepared.preview.existingMemos, 0)
        let result = try await service.restore(prepared)
        XCTAssertEqual(result.importedMemos, 1)
        let context = ModelContext(destination)
        let rows = try context.fetch(FetchDescriptor<StoredMemo>())
        XCTAssertEqual(rows.count, 3)
        let restored = try XCTUnwrap(rows.first { $0.accountKey == "local" && $0.backupId != "keep-me" })
        XCTAssertEqual(restored.content, original.content)
        XCTAssertEqual(restored.createdAt, original.createdAt)
        XCTAssertEqual(restored.updatedAt, original.updatedAt)
        XCTAssertEqual(restored.visibility, .local)
        XCTAssertTrue(restored.pinned)
        XCTAssertEqual(restored.rowStatus, .archived)
        XCTAssertEqual(restored.syncState, .synced)
        XCTAssertNil(restored.serverId)
        restored.content = "edited after restore"
        restored.softDeleted = true
        try context.save()
        let repeated = try await service.restore(prepared)
        XCTAssertEqual(repeated.importedMemos, 0)
        XCTAssertEqual(repeated.skippedMemos, 1)
        let unchanged = try ModelContext(destination).fetch(FetchDescriptor<StoredMemo>())
        XCTAssertTrue(unchanged.contains { $0.content == "edited after restore" && $0.softDeleted })
        XCTAssertTrue(unchanged.contains { $0.content == "existing local content" })
    }

    func testAndroidFixtureRestoresAttachedAndUnattachedFilesAndRollsBackFailedCopy() async throws {
        let archive = try XCTUnwrap(Bundle.module.url(forResource: "android-v1", withExtension: "zip", subdirectory: "Fixtures"))
        let directory = FileManager.default.temporaryDirectory.appendingPathComponent(UUID().uuidString)
        defer { try? FileManager.default.removeItem(at: directory) }
        let destination = try container()
        let service = LocalBackupService(container: destination, resourceDirectory: directory)
        let prepared = try await service.prepareImport(from: archive)
        XCTAssertEqual(prepared.preview.attachments, 2)
        let result = try await service.restore(prepared)
        XCTAssertEqual(result.importedMemos, 1)
        XCTAssertEqual(result.importedAttachments, 2)
        let resources = try ModelContext(destination).fetch(FetchDescriptor<StoredResource>())
        XCTAssertEqual(resources.count, 2)
        XCTAssertEqual(resources.filter { $0.memo == nil }.count, 1)
        for resource in resources {
            XCTAssertEqual(try Data(contentsOf: URL(fileURLWithPath: resource.localPath!)), Data([0, 1, 2, 255, 42]))
            XCTAssertEqual(resource.syncState, .synced)
        }
        let again = try await service.restore(prepared)
        XCTAssertEqual(again.importedAttachments, 0)
        XCTAssertEqual(again.skippedAttachments, 2)
        let reexport = try await service.export()
        defer { try? FileManager.default.removeItem(at: reexport) }
        let reimport = try await service.prepareImport(from: reexport)
        XCTAssertEqual(Set(reimport.data.manifest.attachments.map(\.id)), ["android-resource", "android-unattached"])

        let failingContainer = try container()
        let failedDirectory = directory.appendingPathComponent("rollback")
        let failingService = LocalBackupService(container: failingContainer, resourceDirectory: failedDirectory)
        let damaged = try await failingService.prepareImport(from: archive)
        // First attachment is copied; the second fails before the database commit.
        try FileManager.default.removeItem(at: damaged.data.files["attachments/1"]!)
        do {
            _ = try await failingService.restore(damaged)
            XCTFail("Restore should fail")
        } catch { }
        let failedContext = ModelContext(failingContainer)
        XCTAssertEqual(try failedContext.fetchCount(FetchDescriptor<StoredMemo>()), 0)
        XCTAssertEqual(try failedContext.fetchCount(FetchDescriptor<StoredResource>()), 0)
        XCTAssertTrue(try FileManager.default.contentsOfDirectory(atPath: failedDirectory.path).isEmpty)
    }

    func testEmptyAccountExportsAndDeletedMemosAreExcluded() async throws {
        let container = try container()
        let service = LocalBackupService(container: container)
        let empty = try await service.export()
        defer { try? FileManager.default.removeItem(at: empty) }
        let preview = try await service.prepareImport(from: empty)
        XCTAssertEqual(preview.preview.memos, 0)
        let context = ModelContext(container)
        memo(context).softDeleted = true
        try context.save()
        let deleted = try await service.export()
        defer { try? FileManager.default.removeItem(at: deleted) }
        let deletedPreview = try await service.prepareImport(from: deleted)
        XCTAssertEqual(deletedPreview.preview.memos, 0)
    }
}
